version: 2

project_name: imap

builds:
  - id: imap_targz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: targz
    ids: ["imap_targz"]
    formats: ["tar.gz"]

dockers_v2:
  - images:
      - "creativeprojects/imap"
      - "ghcr.io/creativeprojects/imap"
    dockerfile: build/Dockerfile
    ids:
      - imap_targz
    tags:
      - "{{ .RawVersion }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "IMAP tools: backup, copy, move your emails between servers and locally"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64

release:
  disable: true
