project_name: imap

builds:
  - id: imap_targz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: targz
    builds:
      - imap_targz
    format: tar.gz

dockers:
  - image_templates:
      - "creativeprojects/imap:latest-amd64"
      - "creativeprojects/imap:{{ .RawVersion }}-amd64"
    ids:
      - imap_targz
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
      - "--build-arg=ARCH=amd64"

  - image_templates:
      - "creativeprojects/imap:latest-arm64v8"
      - "creativeprojects/imap:{{ .RawVersion }}-arm64v8"
    ids:
      - imap_targz
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
      - "--build-arg=ARCH=arm64"

docker_manifests:
  - name_template: creativeprojects/imap:{{ .RawVersion }}
    image_templates:
      - creativeprojects/imap:{{ .RawVersion }}-amd64
      - creativeprojects/imap:{{ .RawVersion }}-arm64v8

  - name_template: creativeprojects/imap:latest
    image_templates:
      - creativeprojects/imap:latest-amd64
      - creativeprojects/imap:latest-arm64v8

release:
  disable: true
