name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.25']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: "go test -v -short -race -coverprofile='coverage.out' ./..."
      shell: bash

    - name: Code coverage
      uses: codecov/codecov-action@v5
      with:
        env_vars: OS,GO
        files: ./coverage.out
        flags: unittests
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
      continue-on-error: true
